In [1]:
import numpy as np

In [2]:
#3. Create a null vector of size 10
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#6. Create a null vector of size 10 but the fifth value which is 1
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#7. Create a vector with values randing from 10 to 49
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#8. Reverse a vector (first element becomes last)
arr = np.arange(10)
print(arr)
print("## Reversed ##")
print(arr[::-1])

[0 1 2 3 4 5 6 7 8 9]
## Reversed ##
[9 8 7 6 5 4 3 2 1 0]


In [6]:
#9. Create a 3x3 matric with values randing from 0 to 8
arr = np.arange(9).reshape((3,3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#10. Find indices of non-zero elements from [1,2,0,9,4,0]
arr = np.array([1,2,0,9,4,0])
print(np.where(arr != 0))
print(np.nonzero(arr))


(array([0, 1, 3, 4]),)
(array([0, 1, 3, 4]),)


In [15]:
#11. Create a 3x3 identity matrix
arr1 = np.eye(3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#12. Create a 3x3x3 array with random values
arr = np.random.randn(27).reshape(3,3,3)
print(arr)

arr1 = np.random.random((3,3,3))
print(arr1)

[[[ 0.72681118  1.07615181 -0.93020372]
  [ 0.67776624 -0.24659763 -0.69092744]
  [ 0.24561025  1.39030743 -0.09857325]]

 [[ 1.16226889  0.14957385  0.44113435]
  [-0.69290925 -0.49167    -0.53871596]
  [ 0.30549777 -0.13644474 -0.13768893]]

 [[ 0.62706747  1.43976595  0.7049763 ]
  [-0.49426272  0.01521092 -0.74059881]
  [ 0.4493396   3.08858392 -0.7719786 ]]]
[[[0.57497063 0.25016441 0.33117325]
  [0.28687881 0.96023245 0.6601462 ]
  [0.73683103 0.19722735 0.00365761]]

 [[0.18400951 0.30009941 0.98485783]
  [0.66817872 0.17756751 0.16467175]
  [0.98185984 0.47163779 0.3938059 ]]

 [[0.80051364 0.35883034 0.76113042]
  [0.89508026 0.266341   0.05321799]
  [0.94758105 0.59906238 0.84149207]]]


In [25]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
arr = np.random.random((10, 10))
print(arr)
print(arr.max())
print(arr.min())

[[0.47800534 0.33130414 0.72170224 0.64539378 0.45272782 0.21673895
  0.21579432 0.91829139 0.84672194 0.12855828]
 [0.28206716 0.45035488 0.43436143 0.18375028 0.99242568 0.40426218
  0.81985009 0.66596576 0.01447895 0.68269641]
 [0.18781253 0.61366828 0.65258493 0.79155647 0.28430325 0.35593077
  0.44273662 0.60000515 0.05229507 0.73564612]
 [0.10936241 0.85949046 0.81108007 0.56429716 0.9889073  0.66260556
  0.44646535 0.0150886  0.40267613 0.56703828]
 [0.40627617 0.6082073  0.97062287 0.0255415  0.7077029  0.94128117
  0.44574715 0.16168596 0.7613284  0.76844433]
 [0.05784926 0.85415347 0.80007213 0.37556827 0.22676441 0.42047786
  0.14295417 0.44357476 0.80692744 0.24950449]
 [0.18521154 0.81951844 0.35412362 0.68189773 0.500634   0.4613295
  0.76317044 0.7756336  0.16177047 0.41640272]
 [0.94780455 0.69147739 0.53712297 0.75491468 0.84666515 0.8352825
  0.28694433 0.21208171 0.63414217 0.69370493]
 [0.59011911 0.35338737 0.98069287 0.87417324 0.62788858 0.26921003
  0.33534455 0

In [26]:
#14. Create a random vector of size 30 and find the mean value
arr = np.random.random(30)
print(arr.mean())

0.47185784529379415


In [28]:
#15. Create a 2d array with 1 on the border and 0 inside
arr = np.ones((3,3))
#arr[1][1] = 0
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
