In [38]:
# May 16, 2018 - Wednesday
import numpy as np

In [11]:
xarr = np.arange(1.1, 1.6, 0.1)
yarr = np.arange(2.1, 2.6, 0.1)
cond = np.array([True, False, True, True, False])

# take a value form xarr whenever the corresponding value in cond is True else take value from yarr

# list comprehension implementation
# cons with this approach:
# - Will not be very fast for large arrays because all the work is being done in interpreted Python code.
# - This implementation will not work with multi dimensional arrays.
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print("list comprehension: {}".format(result))
%timeit [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

# np.where implementation
result = np.where(cond, xarr, yarr)
print("np.where: {}".format(result))
%timeit np.where(cond, xarr, yarr)


list comprehension: [1.1, 2.2, 1.3000000000000003, 1.4000000000000004, 2.5000000000000004]
The slowest run took 5.14 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.14 µs per loop
np.where: [1.1 2.2 1.3 1.4 2.5]
The slowest run took 6.32 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.11 µs per loop


In [24]:
# Mathematical and Statistical methods
arr = np.random.randn(4,5)
print(arr)
print("Mean: {}".format(arr.mean()))
print("Sum: {}".format(arr.sum()))

# Functions like mean, sum take an optional axis argument that computes the
# statistic over the given axis.

# the following 2 lines compute mean, sum across the columns
print("Mean on axis=1: {}".format(arr.mean(axis=1)))
print("Sum on axis=1: {}".format(arr.sum(axis=1)))

# compute sum across the rows
print("Sum on axis=0: {}".format(arr.sum(axis=0)))

[[ 1.5837535  -0.91619305  0.53203777  0.59315364  0.5890131 ]
 [ 0.04447702  0.24937974  0.5746041   0.53209824 -1.22144794]
 [-2.17146425 -0.73129384 -0.67400433  0.55720018  0.54632832]
 [-1.21118989 -0.41249148 -1.27702127  1.29853531 -0.09212458]]
Mean: -0.08033248571145093
Sum: -1.6066497142290188
Mean on axis=1: [ 0.47635299  0.03582223 -0.49464679 -0.33885838]
Sum on axis=1: [ 2.38176496  0.17911115 -2.47323393 -1.6942919 ]
Sum on axis=0: [-1.75442362 -1.81059863 -0.84438373  2.98098737 -0.1782311 ]


In [32]:
# methods for boolean array

arr = np.random.randn(100)
bools = arr > 0

# boolean values are coerced to 1 (True) or 0 (False).
# sum is often used as a means of counting True values in a boolean arrzay.
(arr > 0).sum()

# any, all

print("any: {}".format(bools.any()))

print("all: {}".format(bools.all()))

any: True
all: False


In [46]:
arr1 = np.random.randint(10, size=(100))
arr2 = np.random.randint(5, size=(100))

# unique
print(np.unique(arr))

# intersection
print(np.intersect1d(arr1, arr2))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
